### ISSUE TITLE
Passwords met een vertical bar (|) erin gaan fout

### ISSUE THREAD

**Issue by JeroenHeemskerk** [lydiavangammeren/educom-webshop-database#10]
Doordat je een explode doet op het | symbool gaat het fout als iemand een | symbool in zijn password gebruikt,
https://github.com/lydiavangammeren/educom-webshop-database/blob/772ca8f609e22dd8d41900366131c87269093c2e/file_repository.php#L11
Kijk naar de derde optie van explode om te zorgen dat er maar maximaal 3 indexen in de array komen

**Comment by lydiavangammeren** [comment]
explode wordt niet langer gebruikt in mijn code
