### ISSUE TITLE
Users kunnen niet inloggen als de user niet de laatste regel in de file is.

### ISSUE THREAD

**Issue by JeroenHeemskerk** [lydiavangammeren/educom-webshop-database#11]
Als je probeert in te loggen met een gebruiker die niet de laatste in de file is, zal dit mislukken.
Dit komt omdat er een 'enter' uit de file is gelezen die aan het password wordt geplakt en deze regel retourneerd dan het password met de enter eraan geplakt;
https://github.com/lydiavangammeren/educom-webshop-database/blob/772ca8f609e22dd8d41900366131c87269093c2e/file_repository.php#L13
Beter is het om alle velden schoon te maken door de ```trim``` functie te gebruiken
```PHP
$user = array("email" => trim($user_data[0]), "name" => trim($user_data[1]), "password" => trim($user_data[2])); 
```

**Comment by lydiavangammeren** [comment]
Ik heb nu $user = $row staan op regel 33, is dat wel ok?

**Comment by JeroenHeemskerk** [comment]
Ja dat klopt, de hele rij die je uit de database terug krijgt is de $user
